[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "NEGradient_GenePriority"
readme = "README.md"
description = "Non-Euclidean-Gradient-Methods-for-Matrix-Completion-in-Gene-Prioritization"
classifiers = ["Programming Language :: Python :: 3.11"]
requires-python = ">=3.11"
dynamic = ["version", "dependencies"]

[tool.setuptools]
packages = ["NEGradient_GenePriority"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.pytest.ini_options]
pythonpath = ["."]
