[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "NEGradient-GenePriority"
readme = "README.md"
description = "Non-Euclidean-Gradient-Methods-for-Matrix-Completion-in-Gene-Prioritization"
classifiers = ["Programming Language :: Python :: 3.11"]
requires-python = ">=3.11"
dependencies = []
dynamic = ["version"]


[tool.setuptools]
packages = ['NEGradient-GenePriority']


[tool.pytest.ini_options]
pythonpath = ["."]
 